# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

ENV['RCT_USE_PREBUILT_RNCORE'] = '0'
$RNFirebaseDisableSPM = true

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'EllisThreadmarks' do
  project 'EllisThreadmarks.xcodeproj'
  config = use_native_modules!

  # FirebaseCoreInternal is Swift and needs GoogleUtilities to expose a module map.
  pod 'GoogleUtilities', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# prepare_react_native_project!

# use_frameworks! :linkage => :dynamic

# target 'EllisThreadmarks' do
#   project 'EllisThreadmarks.xcodeproj'
#   config = use_native_modules!

#   pod 'MMKVCore', :path => File.expand_path('~/MMKVCoreLocal')

#   use_react_native!(
#     :path => config[:reactNativePath],
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   post_install do |installer|
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false
#     )
#   end
# end
